title:        Algorotoscope
url:          http://algorithmic.rotoscope.work/

tag: Images

logo:         https://s3.amazonaws.com/kinlane-productions/api-evangelist-site/api-evangelist-logo-algorotoscope.png
logo_width:   80
logo_bottom_padding: 10

version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     kramdown

permalink: /:categories/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]

paginate: 150
paginate_path: "/updates/page:num"

github_user: api-evangelist
github_repo: basics
github_branch: master

# Footer
footer_title: API Evangelist
footer_link: http://apievangelist.com
footer_image_source: https://s3.amazonaws.com/kinlane-productions/footer/empowered-by-you-banner.png
footer_image_width: 60

collections:
  works:
    output: true
    permalink: /works/:path/
  collections:
    output: true
    permalink: /collections/:path/
